Clean up graplctl and e2e tests
grapl-security/grapl pull request #1250
Opened 2021-11-03 22:33 UTC by jgrillo-grapl

### Which issue does this PR correspond to?
NA

### What changes does this PR make to Grapl? Why?
This PR removes a bunch of AWS Lambda, Docker Swarm based functionality from `graplctl` and a Buildkite testing pipeline which depends on it.

### How were these changes tested?
Automated tests

2021-11-03 22:39 UTC, wimax-grapl approved these changes
my fav type of PR

2021-11-04 14:08 UTC, christophermaier requested changes

2021-11-04 14:08 UTC, christophermaier commented on .buildkite/pipeline.testing.yml
> ----
Due to the nature of the pipelines, we should leave this file in place... you can have a dummy step that just runs `echo "Do some real tests later"`.

2021-11-04 15:52 UTC, christophermaier approved these changes

2021-11-04 16:17 UTC, merged