Resolve addresses for dgraph
grapl-security/grapl pull request #266
Opened 2020-09-17 01:26 UTC by colin-grapl

### Which issue does this PR correspond to?
None, hotfix.

### What changes does this PR make to Grapl? Why?
Due to changes in how DGraph is deployed we have to change the client construction.

### How were these changes tested?
This PR is how we'll be testing them.

2020-09-17 21:24 UTC, wimax-grapl approved these changes

2020-09-21 23:18 UTC, jgrillo-grapl requested changes

2020-09-21 23:18 UTC, jgrillo-grapl commented on src/rust/graph-merger/src/main.rs
> +    let is_local = std::env::var("IS_LOCAL")
There's a function for this in grapl-common

2020-09-22 00:08 UTC, jgrillo-grapl approved these changes

2020-09-23 17:25 UTC, merged