Internal 126 downgrade grpc
grapl-security/grapl pull request #477
Opened 2020-12-08 18:22 UTC by andrea-grapl

### What changes does this PR make to Grapl? Why?

Downgrade grpc to see if updated version introduced bug in retrieving graph

### How were these changes tested?

Locally + Manually.

2020-12-08 18:42 UTC, jgrillo-grapl requested changes
Seems like something wrong with the dgraph-js version

2020-12-08 18:42 UTC, jgrillo-grapl commented on package.json
> +    "dgraph-js": "^20.3.1",
We run DGraph version 20.07.1. It's not clear whether the JS client supports this version from the table here: https://github.com/dgraph-io/dgraph-js#supported-versions

Looking at the releases page, the most recent release is 20.03.0: https://github.com/dgraph-io/dgraph-js/releases

Did you find version 20.3.1 published somewhere? It doesn't seem like it should exist...

2020-12-08 19:29 UTC, jgrillo-grapl requested changes

2020-12-08 19:29 UTC, jgrillo-grapl commented on package.json
> +    "dgraph-js": "^20.3.0",
This should be `20.3.0` not `^20.3.0`

2021-01-07 18:50 UTC, andrea-grapl commented
This was not causing the issue with DGraph. Closing issue.

2021-01-07 18:50 UTC, closed without merging