Sqs lambda update
grapl-security/grapl pull request #485
Opened 2020-12-14 18:10 UTC by colin-grapl

### Which issue does this PR correspond to?
None, this is an ad-hoc project to improve some of the costs regarding our lambda executions.

### What changes does this PR make to Grapl? Why?

* Updates to the latest sqs-lambda, which allows us to control aspects of lambda execution more easily.
* Latest sqs-lambda fixes a bug where messages may be processed repeatedly
* Reduces the number of retries on each SQS lambda

### How were these changes tested?

I'm in the process of testing these. This is a draft PR.

2020-12-14 18:38 UTC, inickles-grapl requested changes

2020-12-14 18:38 UTC, inickles-grapl commented on src/rust/Cargo.lock
> + "sqs-lambda 0.20.23",
I see a number of these for 0.20.23, but they shouldn't they all be 0.21.0?

2020-12-14 19:01 UTC, inickles-grapl approved these changes

2020-12-15 23:05 UTC, wimax-grapl commented
---- test_service stdout ----
thread 'test_service' panicked at 'DYNAMIC_SESSION_TABLE: NotPresent', grapl-config/src/lib.rs:185:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

2020-12-16 23:55 UTC, inickles-grapl commented on src/rust/grapl-config/Cargo.toml
> +sqs-lambda = "0.21.0"
Any particular reason we set patch number for this but not others?

Same for graph-generator-lib

2020-12-17 21:27 UTC, merged