Internal 280 cypress auth
grapl-security/grapl pull request #635
Opened 2021-02-24 23:57 UTC by andrea-grapl

### Which issue does this PR correspond to?

https://github.com/grapl-security/issue-tracker/issues/280

### What changes does this PR make to Grapl? Why?
Adds testing for authentication because we previously didn't have any 

### How were these changes tested?
Using Cypress: 
`make up`
`cd src/test`
`npx cypress open`
click `login.js`

2021-02-26 01:14 UTC, wimax-grapl commented on test/cypress/integration/login.js
> +describe("sanity check", () => {
probably not needed

2021-02-26 01:14 UTC, wimax-grapl commented on test/cypress/integration/login.js
> +
could we replace all the tabs here with four spaces, if possible?

2021-02-26 01:14 UTC, wimax-grapl commented on test/cypress.json
> +    "chromeWebSecurity": false
is this line absolutely needed?

2021-02-26 02:39 UTC, ajm-grapl requested changes
An explicit assertion on the jwt token causes the test to fail

2021-02-26 02:39 UTC, ajm-grapl commented on test/cypress.json
> +    "chromeWebSecurity": false
I was able to get passes with `make test-integration` without this line, FWIW.

2021-02-26 02:39 UTC, ajm-grapl commented on test/cypress/integration/login.js
> +		cy.getCookie("grapl_jwt");
I tried this as `cy.getCookie("grapl_jwt").should('exist')` and got a failure, saying the cookie was null.

AFAICT the Cypress API will only fail for unexpected conditions if you use an assertion method, like "should".

2021-03-03 01:17 UTC, andrea-grapl commented on test/cypress.json
> +    "chromeWebSecurity": false
It's for CORS

2021-05-07 18:29 UTC, closed without merging