Update rust to 1.50
grapl-security/grapl pull request #667
Opened 2021-03-09 09:22 UTC by colin-grapl

### Which issue does this PR correspond to?
internal 260

### What changes does this PR make to Grapl? Why?
Updates the rust compiler to 1.50

### How were these changes tested?
Local tests

2021-03-09 16:25 UTC, christophermaier requested changes
We should update the nightly version for formatting, as well as attend to the other tasks outlined on the issue: https://github.com/grapl-security/issue-tracker/issues/260

2021-03-09 16:58 UTC, colin-grapl commented on src/python/engagement_edge/src/engagement_edge.py
> +
The typecheck is failing otherwise, I'm assuming due to some sort of dependency update.

2021-03-09 17:06 UTC, christophermaier commented on src/python/engagement_edge/src/engagement_edge.py
> +
Strictly speaking, that should be a separate PR. I can't imagine how updating Rust would cause Python code to stop typechecking correctly.

2021-03-31 15:26 UTC, inickles-grapl commented
Closing this as we've jumped beyond to 1.51: https://github.com/grapl-security/grapl/pull/707

2021-03-31 15:26 UTC, closed without merging